# Generated by Django 4.0.4 on 2022-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_visit_by_technician',
            field=models.DateField(blank=True, null=True),
        ),
    ]
