# Generated by Django 4.0.4 on 2022-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to=''),
        ),
    ]
