# Generated by Django 4.0.4 on 2022-05-01 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_application_date_of_visit_by_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
